services:

  app:
    build:
      context: ../..
      dockerfile: deploy/app/Dockerfile
      target: app
      args:
        NODE_VERSION: ${NODE_VERSION:-24}
        NPM_VERSION: ${NPM_VERSION:-10}
    image: ${APP_IMAGE_NAME:-starfox}:${VERSION:-latest}
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mariadb:11.0.2-jammy
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - db:/var/lib/mysql
      - ../database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      retries: 5
      timeout: 5s
    restart: unless-stopped

volumes:
  db:
